### ISSUE TITLE
Check code with Brakeman http://brakemanscanner.org/, insure code is free of errors.

### ISSUE THREAD

**Issue by gitshiva** [safehavennetwork/safehaven_portal#143]

**Comment by anishiva** [comment]
Ok

**Comment by anishiva** [comment]
Found and fixed a - Dynamic Render Path - Warning @ organization_controller/release_pets(method)

**Comment by anishiva** [comment]
There are other (15) issues with warning type "Unscoped Find". Does this need fixing?

**Comment by anishiva** [comment]
"Unscoped Find" Warning will be addressed later

**Comment by anishiva** [comment]
Done!
