### ISSUE TITLE
Add this file to the public assests folder i.e. <approot>/public

### ISSUE THREAD

**Issue by gitshiva** [safehavennetwork/safehaven_portal#145]
unzip file in the public directory
[file.zip](https://github.com/safehavennetwork/safehaven_portal/files/234540/file.zip)

this file is required for newrelic to function properly.

**Comment by anishiva** [comment]
ok

**Comment by anishiva** [comment]
The unzipped new relic file has been add to the public directory.

**Comment by anishiva** [comment]
DONE!
