### ISSUE TITLE
Add secured by logo to https://secure.thesafehavennetwork.org

### ISSUE THREAD

**Issue by gitshiva** [safehavennetwork/safehaven_portal#150]
![protected-by-logo](https://cloud.githubusercontent.com/assets/7301747/14805622/871f1f66-0b3b-11e6-99a6-435900dd73b4.png)
place the logo as seen above by adding this code to our page:

`<iframe src="https://www.tinfoilsecurity.com/free_badge_iframe?type=grey&size=2" sandbox="allow-popups" scrolling="no" frameborder="0" allowTransparency="true" style="border:none; overflow:hidden; width:115px; height:35px;"></iframe>`

**Comment by gitshiva** [comment]
== please add code below for logo == 
<iframe src="https://www.tinfoilsecurity.com/free_badge_iframe?type=grey&size=2" sandbox="allow-popups" scrolling="no" frameborder="0" allowTransparency="true" style="border:none; overflow:hidden; width:115px; height:35px;"></iframe>

**Comment by gitshiva** [comment]
`<iframe src="https://www.tinfoilsecurity.com/free_badge_iframe?type=grey&size=2" sandbox="allow-popups" scrolling="no" frameborder="0" allowTransparency="true" style="border:none; overflow:hidden; width:115px; height:35px;"></iframe>`

**Comment by anishiva** [comment]
image stored in asset folder and linked to tinfoil

**Comment by anishiva** [comment]
Done for now!
