### ISSUE TITLE
on secure.tshn.org update about-us to point to http://thesafehavennetwork.org/what-we-do/

### ISSUE THREAD

**Issue by gitshiva** [safehavennetwork/safehaven_portal#152]
this is because thesafehavennetwork.org page has been re-designed, so some URLs need updating:

![tshn-about-us](https://cloud.githubusercontent.com/assets/7301747/14805724/b6ae7c3a-0b3c-11e6-917a-092ef6a01338.png)

**Comment by anishiva** [comment]
About Us link in secure_portal updated
Done!
