### ISSUE TITLE
Add unique case numbers to clients

### ISSUE THREAD

**Issue by themoffatt** [safehavennetwork/safehaven_portal#21]
Client info should include a unique identifying case number

**Comment by katzenbar** [comment]
@themoffatt What needs to be different than the rails model id to make this work in the app?

**Comment by themoffatt** [comment]
I'm cool with using the client.id for now.  I'm not sure if Jess wanted there to be case numbers on the Application, so that a client could have multiple cases or not.

**Comment by themoffatt** [comment]
This is just about done

**Comment by themoffatt** [comment]
This gets us what we need, I'm just trying to bring down the queries it takes to get there.

```
 pets = Client.includes(:pets).where('pets.organization' => nil).map do |c|
   {
     client_id: c.id,
     pet_count: c.pets.count,
     breeds:    c.pets.map(&:breed).uniq,
     types:     c.pets.map{|p| p.pet_type.try(:pet_type)}.uniq,
     weights:   c.pets.map(&:weight).uniq
   }
  end
```

**Comment by themoffatt** [comment]
We can use counter_cache: true to get rid of the count(*) queries

**Comment by themoffatt** [comment]
Other than this though, the actual flow needs to change so that a Shelter only has the option to accept all pets for a given client, so as to not break them up.

**Comment by themoffatt** [comment]
Almost done!  28 queries knocked down to a single query!  The new workflow forms are almost done.

```
 Client.includes(:pets, pets: :pet_type).where('pets.organization' => nil).map do |c|
      @pets = c.pets
      OpenStruct.new({
        client_id: c.id,
        pet_count: c.pets.size,
        breeds:    breeds,
        types:     types,
        weights:   weights
      })
    end
```

**Comment by themoffatt** [comment]
We're now using the client.id for this.  Resolved in https://github.com/safehavennetwork/safehaven_portal/pull/42
