### ISSUE TITLE
Clear "Your Pet" fields on new client form

### ISSUE THREAD

**Issue by themoffatt** [safehavennetwork/safehaven_portal#23]
When adding a client at /organization/1/new_client, the short form for "Your Pets" should clear the fields when "Add Pet" is clicked and the pet gets added to the list.

**Comment by katzenbar** [comment]
@themoffatt Can you assign this one to me?

**Comment by themoffatt** [comment]
Thanks @ktornwall !

**Comment by katzenbar** [comment]
PR merged.
