### ISSUE TITLE
Disclaimer when signing up on portal

### ISSUE THREAD

**Issue by SafeHavenED** [safehavennetwork/safehaven_portal#36]
When someone clicks on the link (on the SHN website) to connect to the secure website and sign up as a new user, could we have a disclaimer (or something) pop up that says something like this:

"PLEASE NOTE: The Safe Haven Network Referral Program is based in Chicago and is currently only available to clients in Chicago and the surrounding suburbs.  If you require services outside the Chicago area, please click here [http://www.awionline.org/safe-havens] to find a safe haven in your area.  You may subscribe to The Safe Haven Network's e-newsletter here [http://eepurl.com/4kdfX] to learn about future expansions of The Safe Haven Network's Referral Program."

**Comment by tacocatcodes** [comment]
@SafeHavenED @themoffatt is something like this what you're looking for? (Granted I suck at styling, but this seemed like an easy task to knock out this way). This is the modal window after clicking the "new user? sign up" button on `/users/sign_in`.

<img width="600" alt="screen shot 2015-09-09 at 19 02 19" src="https://cloud.githubusercontent.com/assets/4249785/9777099/5c05144a-5725-11e5-9e12-5b257ad157a8.png">

**Comment by themoffatt** [comment]
@laneatomic - This looks like a great start.  Want to put out a pull request and maybe I can help with the styling?  It looks like all we need to do is clean up that "Not sure?" button.  Now that I see it like this, I vote we add a third column and make it it's own section.  What do you think?

**Comment by tacocatcodes** [comment]
PR is in. Right now the css for the disclaimer is inline in the slim. I can try making it a 3rd column and see how that looks, but it might be a bit tight even if we widen the modal imho. It's a pretty information-dense disclaimer.

edit: I also tweaked it slightly, so it'll have slightly more margin than it does in the above screenshot (I had indentation screwed up in the slim when I took the screenshot)

**Comment by themoffatt** [comment]
Now that I'm looking at it closer, we don't even have the "Not sure?" button linked to anything.  Let's ditch it all together for now.  We can reincorporate something for that later if it's needed.

**Comment by tacocatcodes** [comment]
Removed the button. `modal_footer` looks a lot more acceptable now, however the fact that the two boxes aren't the same height is also annoying me, and I can't figure out how to fix that. I think that'd be the only other style change needed for this issue?

**Comment by tacocatcodes** [comment]
Disregard, resized the left image to 11.25em (from 12em) and it fits perfectly.

<img width="506" alt="screen shot 2015-09-09 at 20 46 00" src="https://cloud.githubusercontent.com/assets/4249785/9778280/e29099fe-5733-11e5-8d31-57a93b4e8bb0.png">

**Comment by themoffatt** [comment]
Awesome!  Thanks man!  It's merged

**Comment by tacocatcodes** [comment]
:beers:
