### ISSUE TITLE
Switch to Postgresql

### ISSUE THREAD

**Issue by themoffatt** [safehavennetwork/safehaven_portal#55]

**Comment by katzenbar** [comment]
Lovelovelove

**Comment by themoffatt** [comment]
:+1:   Amazon emailed Jess that a MySQL update was available.  I figure, why do that when we can update our system overall by using postgresql instead! :dancer:

**Comment by themoffatt** [comment]
https://github.com/safehavennetwork/safehaven_portal/pull/75
