### ISSUE TITLE
Clients can see their application?

### ISSUE THREAD

**Issue by themoffatt** [safehavennetwork/safehaven_portal#57]
We should probably have a way for clients to log in and check the status of their application.  They should be able to edit their information, change their password, etc.  We could probably also let them view contact information for their advocate and the Shelter their pets are placed with.  If nothing else, there needs to be an email address or contact info somewhere that is very obvious for "Check the status of my application" or something.

**Comment by bdub3** [comment]
Do we want clients to have to create a login? Or should we allow them to check on the status of their app just by entering the case number?

**Comment by themoffatt** [comment]
We need to talk to Jess ( @SafeHavenED ) about this.  After thinking about it, I'm not sure what she'll want to do here.  Some clients may not be able or willing to provide an email.  Maybe we can just make it optional, and message that to the client.  "In order to check or update your application, you must provide an email address to verify your account and log back in".  We might be able to easily add the client class to be used by the Devise gem for authentication.  (try to login using the User class, then try the Client class)n

**Comment by themoffatt** [comment]
This is getting closed until the overall feature is thought out more and discussed with @SafeHavenED .
